import type { ActMeta } from "./types";

export const ACTS: ActMeta[] = [
  {
    id: "I",
    glyph: "Α",
    index: 1,
    title: "The Genesis Mire",
    subtitle: "Devcons 0–1 · Before everything",
    land: "Berlin 2014, London 2015. The protocol is barely walking. Vitalik speaks in roadmaps; Casper is a whisper, Plasma will not be conceived for two years, the first vulnerability that will be named reentrancy has yet to drain its first contract.",
    mood: "Hopeful, dense with foreshadowing, often technically dated. Many talks here are about projects that no longer exist. They are kept on the path because they show what the early vow felt like.",
    prereq: "None. Begin here.",
    runes: "Constraint, Account, Storage, Slashing, Roadmap.",
  },
  {
    id: "II",
    glyph: "Β",
    index: 2,
    title: "The Substrate Sanctum",
    subtitle: "EVM · Solidity · Security",
    land: "The world's physics. The EVM, the languages that compile to it, the bugs that exploit it, the auditors who hunt those bugs. This is the longest Land; many Tarnished spend their entire path here and never leave.",
    mood: "Professional, surgical, sometimes grim. Many of these talks were given in the shadow of an exploit. Listen for the year — D2 is pre-DAO, D3 is post-DAO and post-Parity-multisig, D5 onward is mature tooling.",
    prereq: "Act I. You must know what an account and a transaction are before you can read about how they break.",
    runes: "Reentrancy, Threat Model, Bytecode, Yul, Gas, EOF, Class.",
  },
  {
    id: "III",
    glyph: "Γ",
    index: 3,
    title: "The Markets of the Dead",
    subtitle: "DeFi · MEV · Cryptoeconomics",
    land: "The protocol's economic gravity, and the predators that arose to graze on it. Where the Substrate Sanctum taught you how contracts work, this Land teaches you what happens when contracts hold money.",
    mood: "Adversarial. The talks here often feel like field reports from a dark forest. Read in chronological order to feel the field harden — D5 is pre-MEV-naming, D6 is mid-PBS, D7 is the post-Flashbots empirical era.",
    prereq: "Act II. AMMs and lending protocols are smart contracts; you must already be able to read those.",
    runes: "Liquidity, AMM, CDP, MEV, PBS, LVR, Tension. At the end of this Land you choose a class.",
  },
  {
    id: "IV",
    glyph: "Δ",
    index: 4,
    title: "The Engine Room",
    subtitle: "Consensus · Staking · Clients · P2P",
    land: "The protocol itself. Casper, the Beacon Chain, validators, slashing, gossipsub, light clients. This is the Land of the people who run Ethereum, not those who build on it.",
    mood: "Engineering rooms at 3 a.m. Detailed. Often dry. Watch for the Heroes-of-the-Merge talk — that is the keystone.",
    prereq: "Act I, plus at least the consensus passages in Act III if you went deep on cryptoeconomics.",
    runes: "Finality, Slot, Weak Subjectivity, Engine API, SSF, Coordination.",
  },
  {
    id: "V",
    glyph: "Ε",
    index: 5,
    title: "The Frontier",
    subtitle: "Cryptography · ZK · Rollups · AA · Cross-chain",
    land: "The bleeding edge of the protocol, the place where the next decade is being decided. Cryptography, zero-knowledge, rollups, account abstraction, cross-chain.",
    mood: "Heady, mathematical, fast-moving. Many of these talks will be obsolete in three years; they are still on the path because the direction they trace will outlast the specific constructions.",
    prereq: "Act II at least. Strongly recommended: the Cryptography opening of this Act before any ZK talk.",
    runes: "Witness, Trade-off, Trusted Setup, Type-1, Validation, 7702, Defragmentation, Verifiability.",
  },
  {
    id: "VI",
    glyph: "Ζ",
    index: 6,
    title: "The Endgame",
    subtitle: "Privacy · FV · Worlds · Philosophy",
    land: "Specializations. Privacy. Formal Verification. Onchain games. Identity. Public goods. Cypherpunk philosophy. Real-world adoption. The Tarnished who reaches this Land has already walked far.",
    mood: "Strange. Some talks here are deeply technical (FV); others are explicitly philosophical (cypherpunk). The Land of Reeds. Choose what resonates.",
    prereq: "Whatever subset of Acts I–V the specialty draws on.",
    runes: "Whichever you reach for. There is no canonical set.",
  },
];

// Class selection at the end of Act III
export const CLASSES = [
  { glyph: "Ψ", name: "The Magus",     soul: "You bend math into proof. The world is a circuit.",                path: "V (ZK depth) → IV (consensus, lightly) → VI (Privacy, FV)" },
  { glyph: "Ξ", name: "The Sellsword", soul: "You take what is not bolted down. The dark forest is your hunt.", path: "III (MEV depth) → V (Rollups, AA) → IV (PBS, builders)" },
  { glyph: "Λ", name: "The Warden",    soul: "You keep the engine running. Every block. Every slot.",            path: "IV (Consensus, staking, clients) → I revisited → V (DA, sharding)" },
  { glyph: "Π", name: "The Architect", soul: "You design the next protocol. Rollups, AA, cross-chain.",          path: "V (full depth) → IV (engine context) → VI (FV for safety)" },
  { glyph: "Θ", name: "The Smith",     soul: "You build for users. Contracts that hold up under stress.",        path: "II (full depth) → III (DeFi) → V (AA for UX) → VI (FV, Privacy)" },
];
