// Paradigm/Zone lookups built from lib/paradigms.json (definitions) +
// lib/talk-paradigms.json (per-talk classifications, generated by parallel
// subagent classification — see /tmp/tp-classify/ pipeline).
//
// Graceful fallback: if talk-paradigms.json is missing or empty, this module
// returns empty zone lists and the UI can render a "classification pending" state.

import type { Talk, ActId } from "./types";
import { TALKS } from "./talks";
import paradigmsRaw from "./paradigms.json";

export interface ParadigmDef {
  id: string;
  name: string;
  blurb: string;
  seedZones: string[];
}

export const PARADIGMS: Record<string, ParadigmDef> = paradigmsRaw as Record<string, ParadigmDef>;
export const PARADIGM_ORDER: string[] = [
  "privacy", "identity", "markets", "scaling", "consensus",
  "cryptography", "builders-craft", "governance", "ai-agents", "real-world",
];

interface TalkParadigmEntry {
  paradigms: string[];
  zone: string;
  threadIds: string[];
}

// Lazy-load the classification artifact. Returns {} if missing.
let _talkParadigms: Record<string, TalkParadigmEntry> | null = null;
function loadTalkParadigms(): Record<string, TalkParadigmEntry> {
  if (_talkParadigms !== null) return _talkParadigms;
  try {
    // Static import would fail at build if file absent. Use require so missing → empty.
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const data = require("./talk-paradigms.json") as Record<string, TalkParadigmEntry>;
    _talkParadigms = data || {};
  } catch {
    _talkParadigms = {};
  }
  return _talkParadigms;
}

export interface Zone {
  id: string;            // canonical slug
  name: string;          // canonical display name
  paradigm: string;      // paradigm id
  talks: Talk[];         // ordered by tier then year asc
}

export interface ParadigmInAct {
  paradigm: ParadigmDef;
  zones: Zone[];
  totalTalks: number;
}

const TIER_RANK: Record<string, number> = { boss: 0, main: 1, side: 2, chronicle: 3 };
const DEVCON_YEARS = [2014, 2015, 2016, 2017, 2018, 2019, 2022, 2023, 2024];

function yearOf(t: Talk): number {
  const m = (t.event || "").match(/(20\d{2})/);
  if (m) return parseInt(m[1], 10);
  if (t.source === "devcon" && t.ed >= 0 && t.ed < DEVCON_YEARS.length) return DEVCON_YEARS[t.ed];
  return 0;
}

function slugifyZone(name: string): string {
  return name.toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-");
}

// --- Canonical zone → paradigm map ----------------------------------------
// Every seed zone in paradigms.json belongs unambiguously to one paradigm.
// Plus a synonym table that folds LLM-invented variants into a canonical seed.
// Hard rule: a given zone NAME (after canonicalization) lives in exactly ONE paradigm.

interface ZoneRoute {
  paradigm: string;
  canonicalName: string;
}

const ZONE_SYNONYMS: Record<string, ZoneRoute> = (() => {
  const m: Record<string, ZoneRoute> = {};
  for (const pid of PARADIGM_ORDER) {
    const p = PARADIGMS[pid];
    if (!p) continue;
    for (const seed of p.seedZones) {
      m[seed.toLowerCase()] = { paradigm: pid, canonicalName: seed };
    }
  }
  const aliases: Array<[string, string, string]> = [
    ["defi", "markets", "AMMs & DEXes"],
    ["dex", "markets", "AMMs & DEXes"],
    ["amm", "markets", "AMMs & DEXes"],
    ["lending", "markets", "Lending & Stablecoins"],
    ["stablecoin", "markets", "Lending & Stablecoins"],
    ["stablecoins", "markets", "Lending & Stablecoins"],
    ["mev", "markets", "MEV & Searchers"],
    ["searchers", "markets", "MEV & Searchers"],
    ["intents", "markets", "Intents & Solvers"],
    ["solvers", "markets", "Intents & Solvers"],
    ["oracle", "markets", "Oracles"],
    ["price feeds", "markets", "Oracles"],
    ["data feeds", "markets", "Oracles"],

    ["zk circuits", "cryptography", "ZK Circuits"],
    ["zk proofs", "cryptography", "Proof Systems"],
    ["snark", "cryptography", "Proof Systems"],
    ["stark", "cryptography", "Proof Systems"],
    ["plonk", "cryptography", "Proof Systems"],
    ["zero-knowledge", "cryptography", "Proof Systems"],
    ["zero knowledge", "cryptography", "Proof Systems"],
    ["polynomial commitments", "cryptography", "Polynomial Commitments"],
    ["kzg", "cryptography", "Polynomial Commitments"],
    ["bls", "cryptography", "Threshold & BLS"],
    ["threshold signatures", "cryptography", "Threshold & BLS"],
    ["mpc", "cryptography", "Applied Crypto"],

    ["fhe", "privacy", "FHE & MPC"],
    ["homomorphic", "privacy", "FHE & MPC"],
    ["mixer", "privacy", "Mixers"],
    ["mixers", "privacy", "Mixers"],
    ["semaphore", "privacy", "Anonymity Sets"],
    ["anonymity", "privacy", "Anonymity Sets"],
    ["zkemail", "privacy", "TLSNotary & zkEmail"],
    ["tlsnotary", "privacy", "TLSNotary & zkEmail"],
    ["shielded", "privacy", "Shielded State"],
    ["cypherpunk", "privacy", "Cypherpunk Lessons"],

    ["ens", "identity", "Names & ENS"],
    ["names", "identity", "Names & ENS"],
    ["worldcoin", "identity", "Proof of Personhood"],
    ["world id", "identity", "Proof of Personhood"],
    ["personhood", "identity", "Proof of Personhood"],
    ["sybil", "identity", "Proof of Personhood"],
    ["did", "identity", "Verifiable Credentials"],
    ["verifiable credential", "identity", "Verifiable Credentials"],
    ["attestation", "identity", "Attestations"],
    ["attestations", "identity", "Attestations"],
    ["soulbound", "identity", "Soulbound"],
    ["sbt", "identity", "Soulbound"],
    ["reputation", "identity", "Reputation"],

    ["rollup", "scaling", "Rollups"],
    ["rollups", "scaling", "Rollups"],
    ["zkevm", "scaling", "Rollups"],
    ["zk-rollup", "scaling", "Rollups"],
    ["optimistic", "scaling", "Rollups"],
    ["data availability", "scaling", "Data Availability"],
    ["da", "scaling", "Data Availability"],
    ["celestia", "scaling", "Data Availability"],
    ["danksharding", "scaling", "Data Availability"],
    ["bridges", "scaling", "Bridges"],
    ["bridge", "scaling", "Bridges"],
    ["interop", "scaling", "Bridges"],
    ["cross-chain", "scaling", "Bridges"],
    ["sequencer", "scaling", "Sequencers & Preconfs"],
    ["sequencers", "scaling", "Sequencers & Preconfs"],
    ["preconfs", "scaling", "Sequencers & Preconfs"],
    ["preconfirmations", "scaling", "Sequencers & Preconfs"],
    ["appchain", "scaling", "Appchains"],
    ["appchains", "scaling", "Appchains"],
    ["superchain", "scaling", "Appchains"],
    ["stateless", "scaling", "Statelessness"],
    ["storage", "scaling", "Storage Systems"],
    ["storage systems", "scaling", "Storage Systems"],
    ["filecoin", "scaling", "Storage Systems"],
    ["ipfs", "scaling", "Storage Systems"],

    ["beacon chain", "consensus", "Beacon Chain"],
    ["beacon", "consensus", "Beacon Chain"],
    ["validator", "consensus", "Validators & Staking"],
    ["validators", "consensus", "Validators & Staking"],
    ["staking", "consensus", "Validators & Staking"],
    ["solo staking", "consensus", "Validators & Staking"],
    ["restaking", "consensus", "Restaking"],
    ["lst", "consensus", "Restaking"],
    ["liquid staking", "consensus", "Restaking"],
    ["eigenlayer", "consensus", "Restaking"],
    ["finality", "consensus", "Finality"],
    ["casper", "consensus", "Casper Lineage"],
    ["issuance", "consensus", "Issuance"],

    ["client engineering", "consensus", "Client Engineering"],
    ["execution client", "consensus", "Client Engineering"],
    ["consensus client", "consensus", "Client Engineering"],
    ["p2p", "consensus", "P2P Networking"],
    ["p2p networking", "consensus", "P2P Networking"],
    ["libp2p", "consensus", "P2P Networking"],
    ["gossipsub", "consensus", "P2P Networking"],

    ["smart wallets", "builders-craft", "Smart Wallets & UX"],
    ["smart wallet", "builders-craft", "Smart Wallets & UX"],
    ["wallet ux", "builders-craft", "Smart Wallets & UX"],
    ["passkey", "builders-craft", "Smart Wallets & UX"],
    ["passkeys", "builders-craft", "Smart Wallets & UX"],
    ["account abstraction", "builders-craft", "Account Abstraction"],
    ["aa", "builders-craft", "Account Abstraction"],
    ["erc-4337", "builders-craft", "Account Abstraction"],
    ["paymaster", "builders-craft", "Account Abstraction"],

    ["plasma", "scaling", "Plasma & Channels"],
    ["state channels", "scaling", "Plasma & Channels"],
    ["state channel", "scaling", "Plasma & Channels"],
    ["payment channels", "scaling", "Plasma & Channels"],
    ["old paths", "scaling", "Plasma & Channels"],

    ["solidity", "builders-craft", "Solidity & Vyper"],
    ["vyper", "builders-craft", "Solidity & Vyper"],
    ["yul", "builders-craft", "Solidity & Vyper"],
    ["evm", "builders-craft", "EVM Internals"],
    ["evm internals", "builders-craft", "EVM Internals"],
    ["foundry", "builders-craft", "Foundry & Tooling"],
    ["hardhat", "builders-craft", "Foundry & Tooling"],
    ["dev tooling", "builders-craft", "Foundry & Tooling"],
    ["developer tooling", "builders-craft", "Foundry & Tooling"],
    ["tooling", "builders-craft", "Foundry & Tooling"],
    ["audit", "builders-craft", "Audits & Security"],
    ["audits", "builders-craft", "Audits & Security"],
    ["security", "builders-craft", "Audits & Security"],
    ["formal verification", "builders-craft", "Formal Verification"],
    ["fuzzing", "builders-craft", "Audits & Security"],
    ["gas", "builders-craft", "Gas Optimization"],
    ["gas optimization", "builders-craft", "Gas Optimization"],
    ["builders craft", "builders-craft", "Foundry & Tooling"],

    ["dao", "governance", "DAOs"],
    ["daos", "governance", "DAOs"],
    ["governance", "governance", "DAOs"],
    ["voting", "governance", "Voting Systems"],
    ["quadratic", "governance", "Voting Systems"],
    ["public goods", "governance", "Public Goods"],
    ["gitcoin", "governance", "Public Goods"],
    ["funding", "governance", "Funding Mechanisms"],
    ["retropgf", "governance", "Funding Mechanisms"],
    ["coordination", "governance", "Coordination"],
    ["treasury", "governance", "Treasuries"],
    ["treasuries", "governance", "Treasuries"],

    ["agent", "ai-agents", "Agent Frameworks"],
    ["agents", "ai-agents", "Agent Frameworks"],
    ["agentic", "ai-agents", "Agent Frameworks"],
    ["ai agents", "ai-agents", "Agent Frameworks"],
    ["ai & agents", "ai-agents", "Agent Frameworks"],
    ["onchain ai", "ai-agents", "Onchain Inference"],
    ["onchain inference", "ai-agents", "Onchain Inference"],
    ["llm", "ai-agents", "Onchain Inference"],
    ["llms", "ai-agents", "Onchain Inference"],
    ["tee", "ai-agents", "TEEs & Verifiable Compute"],
    ["tees", "ai-agents", "TEEs & Verifiable Compute"],
    ["ai oracle", "ai-agents", "AI Oracles"],
    ["ai oracles", "ai-agents", "AI Oracles"],
    ["ai x defi", "ai-agents", "AI x DeFi"],
    ["ai defi", "ai-agents", "AI x DeFi"],

    ["rwa", "real-world", "RWAs"],
    ["rwas", "real-world", "RWAs"],
    ["tokenization", "real-world", "RWAs"],
    ["regulation", "real-world", "Regulation & Compliance"],
    ["compliance", "real-world", "Regulation & Compliance"],
    ["kyc", "real-world", "Regulation & Compliance"],
    ["institutional", "real-world", "Institutional Adoption"],
    ["enterprise", "real-world", "Institutional Adoption"],
    ["adoption", "real-world", "Institutional Adoption"],
    ["climate", "real-world", "Climate & Impact"],
    ["impact", "real-world", "Climate & Impact"],
    ["regen", "real-world", "Climate & Impact"],
    ["social", "real-world", "Social & Cultural"],
    ["culture", "real-world", "Social & Cultural"],
    ["community", "real-world", "Social & Cultural"],
    ["onboarding", "real-world", "Onboarding"],
    ["education", "real-world", "Onboarding"],
    ["accessibility", "real-world", "Onboarding"],
  ];
  for (const [pat, paradigm, canonical] of aliases) {
    if (!m[pat]) m[pat] = { paradigm, canonicalName: canonical };
  }
  return m;
})();

// Generic zone names that should NOT route — fall through to talk's primary paradigm.
const GENERIC_ZONES = new Set([
  "sponsor workshop", "sponsor demo", "workshop", "workshops",
  "ceremony", "ecosystem talk", "ecosystem panel", "panel",
  "lightning", "music", "keynote", "intro", "introduction",
  "fireside", "ama", "demo", "demos", "talks", "misc",
  "general", "other", "various", "multi-topic", "default",
]);

// Sorted synonym keys (longest first) — for substring fallback matching.
const SORTED_SYNONYM_KEYS: string[] = Object.keys(ZONE_SYNONYMS).sort((a, b) => b.length - a.length);

function routeZone(rawZone: string, talkParadigms: string[]): ZoneRoute | null {
  const norm = rawZone.trim().toLowerCase().replace(/\s+/g, " ");
  if (!norm || GENERIC_ZONES.has(norm)) {
    if (talkParadigms.length === 0) return null;
    return null; // generic name + only talkParadigm context — drop, don't pollute
  }
  if (ZONE_SYNONYMS[norm]) return ZONE_SYNONYMS[norm];
  for (const k of SORTED_SYNONYM_KEYS) {
    if (k.length < 4) continue;
    if (norm.includes(k)) return ZONE_SYNONYMS[k];
  }
  if (talkParadigms.length === 0) return null;
  // No synonym — keep zone in talk's primary paradigm with its original name.
  return { paradigm: talkParadigms[0], canonicalName: rawZone.trim() };
}

// Build per-Act paradigm view. Cached after first call.
const _cache: Record<ActId, ParadigmInAct[]> = {} as Record<ActId, ParadigmInAct[]>;
let _built = false;

function build() {
  if (_built) return;
  _built = true;
  const tp = loadTalkParadigms();
  const acts: ActId[] = ["I", "II", "III", "IV", "V", "VI"];

  // Per-Act → paradigmId → zoneName → Talk[]
  const perAct: Record<ActId, Record<string, Map<string, Talk[]>>> = {} as Record<ActId, Record<string, Map<string, Talk[]>>>;
  for (const a of acts) perAct[a] = {};

  for (const t of TALKS) {
    const entry = tp[t.id];
    if (!entry || !entry.paradigms || entry.paradigms.length === 0) continue;
    const route = routeZone(entry.zone || "", entry.paradigms);
    if (!route) continue;
    if (!PARADIGMS[route.paradigm]) continue;
    const actBucket = perAct[t.act as ActId];
    if (!actBucket) continue;
    if (!actBucket[route.paradigm]) actBucket[route.paradigm] = new Map();
    const zones = actBucket[route.paradigm];
    if (!zones.has(route.canonicalName)) zones.set(route.canonicalName, []);
    zones.get(route.canonicalName)!.push(t);
  }

  for (const actId of acts) {
    const out: ParadigmInAct[] = [];
    const actBucket = perAct[actId];
    for (const pid of PARADIGM_ORDER) {
      const paradigm = PARADIGMS[pid];
      if (!paradigm) continue;
      const zoneMap = actBucket[pid];
      if (!zoneMap || zoneMap.size === 0) continue;

      const zones: Zone[] = [];
      for (const [name, talks] of zoneMap) {
        talks.sort((a, b) => {
          const tr = (TIER_RANK[a.tier] ?? 9) - (TIER_RANK[b.tier] ?? 9);
          if (tr !== 0) return tr;
          return yearOf(a) - yearOf(b);
        });
        zones.push({
          id: `${pid}--${slugifyZone(name)}`,
          name,
          paradigm: pid,
          talks,
        });
      }
      zones.sort((a, b) => b.talks.length - a.talks.length || a.name.localeCompare(b.name));
      out.push({
        paradigm,
        zones,
        totalTalks: zones.reduce((n, z) => n + z.talks.length, 0),
      });
    }
    out.sort((a, b) => b.totalTalks - a.totalTalks);
    _cache[actId] = out;
  }
}

export function getParadigmsInAct(actId: ActId): ParadigmInAct[] {
  build();
  return _cache[actId] || [];
}

export function getEffectiveThreadIdsFromParadigms(): Record<string, string[]> {
  // For lib/auto-threads.ts to merge LLM-suggested threadIds.
  const tp = loadTalkParadigms();
  const out: Record<string, string[]> = {};
  for (const [talkId, entry] of Object.entries(tp)) {
    if (entry.threadIds && entry.threadIds.length > 0) out[talkId] = entry.threadIds;
  }
  return out;
}

export function isClassificationLoaded(): boolean {
  return Object.keys(loadTalkParadigms()).length > 0;
}
